### ISSUE TITLE
Copy Folder Structure?

### ISSUE THREAD

**Issue by SeaDude** [reesemclean/blueprint-examples#4]
Hello,
Thanks for the time and energy you put into this extension. I'm curious if its able to copy Folder structures as well as files.

**Example**: 
- blueprint-templates
  - project_kebabCase_name // folder
    - assets // folder
    - data  // folder
    - index.md
    - meeting1.md
    - requirements.md

Thanks again

**Comment by reesemclean** [comment]
Hey thanks, 

Yes that is one of the biggest use cases for the extension!

I believe you want one more level of folder though, something like:

* blueprint-templates
  * <name of template (what you will select in the menu)>
    * project_kebabCase_name // folder
      * assets // folder
      * data // folder
      * index.md
      * meeting1.md
      * requirements.md

Let me know if that works for you.

**Comment by SeaDude** [comment]
AhA! Thanks for the guidance. That worked great.

**Comment by SeaDude** [comment]
Sorry to bother again, but what is this asking for initially? It just says "value". 
![image](https://user-images.githubusercontent.com/8636973/51090802-b858a200-1736-11e9-8be6-67e6051fad0e.png)
Thanks

**Comment by reesemclean** [comment]
This is the value that will be used in the template where ever you have {{name}} or {{uppercase name}}, etc. or in the file/folder names like __uppercase_name__.
