### ISSUE TITLE
_name_ not working?

### ISSUE THREAD

**Issue by SeaDude** [reesemclean/blueprint-examples#5]
I'm still getting comfortable with the tool here, so I'm likely doing something wrong but, I can't seem to get `_name_` to work in a folder template. 

**Example:**
- Here is the template. I have `0-project-templates` set in `settings` as the template path for Blueprint
![image](https://user-images.githubusercontent.com/8636973/51323748-dfa4bd00-1a1d-11e9-8b96-140d182c9ade.png)
- Right click, new from template
![image](https://user-images.githubusercontent.com/8636973/51323795-0b27a780-1a1e-11e9-81aa-51237a91bb7c.png)
- Choose the template
![image](https://user-images.githubusercontent.com/8636973/51323819-1b3f8700-1a1e-11e9-9eaa-5019e4d80c2b.png)
- **This part needs a description of some kind!** Enter a value for what parameter?
![image](https://user-images.githubusercontent.com/8636973/51323881-3611fb80-1a1e-11e9-98a5-77e461611341.png)
- Enter values for the variables I defined
![image](https://user-images.githubusercontent.com/8636973/51323918-4a55f880-1a1e-11e9-88c1-d642b178f48e.png)
- **New project created, except it requires a refresh.**
![image](https://user-images.githubusercontent.com/8636973/51324019-7cfff100-1a1e-11e9-93b4-5e34ec899e92.png)
- Post-refresh, notice the `_name_` parameter in the folder is not set. 
![image](https://user-images.githubusercontent.com/8636973/51324068-9c971980-1a1e-11e9-9aba-077fb9d574b7.png)

How do I get this to work?

**Comment by reesemclean** [comment]
It’s hard for me to tell but do you have double underscores around name? I.e. __name__ not _name_?

**Comment by SeaDude** [comment]
Aha! No, I did not. When I changed to double underscores on either side, it worked. Sorry, I must have missed that in the docs. 
Thank you very much!
